ProjetoTesteRafa/Models/cliente_empresa_usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProjetoTesteRafa.Models
{
    public class cliente_empresa_usuario
    {
        [Key]
        public int cus_codigo { get; set; }

        [Required(ErrorMessage = "Informe o usuário")]
        [Display(Name = "Usuário:")]
        public string cus_usuario { get; set; }

        [Required(ErrorMessage = "Informe a senha")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha:")]
        public string cus_senha { get; set; }

        [Display(Name = "Lembrar-me?")]
        public bool cus_lembrar_me { get; set; }

        [Display(Name = "Nome:")]
        public string cus_nome { get; set; }

        [Display(Name = "Sorenome:")]
        public string cus_sobrenome { get; set; }

        [Display(Name = "Endereço:")]
        public string cus_endereco { get; set; }

        [Display(Name = "Número:")]
        public string cus_numero { get; set; }

        [Display(Name = "Complemento:")]
        public string cus_complemento { get; set; }

        [Display(Name = "Bairro:")]
        public string cus_bairro { get; set; }

        [Display(Name = "Cidade:")]
        public string cus_cidade { get; set; }

        [Display(Name = "Estado:")]
        public string cus_estado { get; set; }

        [Display(Name = "CEP:")]
        public string cus_cep { get; set; }

        [Display(Name = "Telefone:")]
        public string cus_telefone { get; set; }

        [Display(Name = "E-mail:")]
        public string cus_email { get; set; }

        [Display(Name = "Usuário ativo:")]
        public bool cus_ativo { get; set; }

        [NotMapped]
        public bool cus_ativo_anterior { get; set; }


        [Display(Name = "Empresa")]
        [ForeignKey("cliente_empresa")]
        public int cus_empresa { get; set; }
        public virtual cliente_empresa cliente_empresa { get; set; }



        // Vínculo com a tabela de perfil de acessos
        public virtual IList<perfil_usuario_acesso> cus_perfil_acesso { get; set; }


    }
}

ProjetoTesteRafa/Controllers/ClienteEmpresaUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Security.Cryptography;
using System.Text;
using ProjetoTesteRafa.Models;
using ProjetoTesteRafa.Models.Comum;

namespace ProjetoTesteRafa.Controllers
{
    public class ClienteEmpresaUsuarioController : Controller
    {
        private DataContext db = new DataContext();


        /*****************************************
         *                                       *
         *                INDEX                  *
         *                                       *
         *****************************************/


        // GET: ClienteEmpresaUsuario - Página Index onde serão mostrados os usuários
        [Authorize]
        public async Task<ActionResult> Index()
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pua_ler_clienteempresausuario_index))
                    {
                        // Funciona
                        // a variável em Session precisa ser posta em outra variável com seu tipo antes de ser passada
                        // para ser feito o comparativo e buscar apenas as empresas que fazem parte do usuário em questão
                        var empresa = (int)Session["Empresa"];

                        // busca no banco incluindo a tabela cliente_empresa
                        var cliente_empresa_usuario = db.cliente_empresa_usuario.Include(c => c.cliente_empresa).OrderBy(x => x.cus_nome);

                        //verifica o que cliente_empresa_usuario trouxe do banco e filtra pra mostrar apenas
                        // a empresa que é comparável ao usuário logado
                        var usuario_final = cliente_empresa_usuario.Where(x => x.cus_empresa == empresa);

                        // devolve para a View de forma Assíncrona os dados já filtrados para serem mostrados na View
                        return View(await usuario_final.ToListAsync());
                        
                        // funcional
                        //var cliente_empresa_usuario = new List<cliente_empresa_usuario>(db.cliente_empresa_usuario.Include(c => c.cliente_empresa).ToList().Where(x => x.cus_empresa == (int)Session["Empresa"]));
                        //return View(cliente_empresa_usuario);

                        //Padrão
                        //return View(await cliente_empresa_usuario.ToListAsync());
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_ler_clienteempresausuario_index))
                    {
                        var cliente_empresa_usuario = db.cliente_empresa_usuario.Include(c => c.cliente_empresa).OrderBy(x => x.cliente_empresa.cle_razaosocial_principal);
                        return View(await cliente_empresa_usuario.ToListAsync()); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }



        /*****************************************
         *                                       *
         *                DETAILS                *
         *                                       *
         *****************************************/


        // GET: ClienteEmpresaUsuario/Details/5 - Mostrar os detalhes do usuário selecionado. A numeração no comentário serve para mostrar qual
        //  o índice (o ID do ítem) no banco.
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pua_ler_clienteempresausuario_details))
                    {
                        if (id == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                        cliente_empresa_usuario cliente_empresa_usuario = await db.cliente_empresa_usuario.FindAsync(id);
                        if (cliente_empresa_usuario == null)
                        {
                            return HttpNotFound();
                        }

                        // Valida se o id procurado faz parte da empresa e exiba. Caso contrário, mostra uma
                        // página dizendo que não faz parte da empresa.
                        var empresa = (int)Session["Empresa"];
                        var acesso_empresa = cliente_empresa_usuario.cus_empresa.Equals(empresa);

                        if (!acesso_empresa)
                        {
                            return View("~/Views/Shared/_OutraEmpresa.cshtml");
                        }

                        // Término da validação da empresa

                        return View(cliente_empresa_usuario);
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_ler_clienteempresausuario_details))
                    {
                        if (id == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                        cliente_empresa_usuario cliente_empresa_usuario = await db.cliente_empresa_usuario.FindAsync(id);
                        if (cliente_empresa_usuario == null)
                        {
                            return HttpNotFound();
                        }
                        return View(cliente_empresa_usuario); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }



        /*****************************************
         *                                       *
         *                CREATE                 *
         *                                       *
         *****************************************/


        // GET: ClienteEmpresaUsuario/Create - Mostrar a criação do Usuário da Empresa
        [Authorize]
        public async Task<ActionResult> Create()
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var empresa = (int)Session["Empresa"];
                    cliente_empresa cliente_empresa = await db.cliente_empresa.FindAsync(empresa);

                    if (cliente_empresa.cle_quantidade_usuario_ativo < cliente_empresa.cle_quantidade_usuario)
                    {
                        var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                        if (acesso_perfil != null && acesso_perfil.Any(x => x.pua_lerescrever_clienteempresausuario_create))
                        {
                            //ViewBag.cus_empresa = new SelectList(db.cliente_empresa, "cle_codigo", "cle_razaosocial_principal");
                            ViewBag.cus_empresa = new SelectList(db.cliente_empresa.ToList().Where(x => x.cle_codigo == (int)Session["Empresa"]), "cle_codigo", "cle_razaosocial_principal");
                            ViewBag.Estados = new SelectList(new Estados().ListaEstados(), "data_sigla_estado", "data_nome_estado");
                            return View();
                        }
                        return View("~/Views/Shared/_SemAutorizacao.cshtml"); 
                    }
                    return View("~/Views/Shared/_LimiteExcedido.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_lerescrever_clienteempresausuario_create))
                    {
                        // só põe na lista as empresas onde a quantidade de usuários ativos sejam menores que a quantidade máxima
                        // de usuários que a empresa pode criar, impedindo assim de que seja criados novos usuários sem que
                        // a empresa tenha contratado tal quantidade
                        var items = db.cliente_empresa.ToList().Where(x => x.cle_quantidade_usuario_ativo < x.cle_quantidade_usuario);

ProjetoTesteRafa/Views/ClienteEmpresaUsuario/Delete.cshtml
@model ProjetoTesteRafa.Models.cliente_empresa_usuario



@{
    ViewBag.Title = "Apagar";
}


<div class="content pb-1">
    <div class="container-fluid">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        @if (Session["Empresa"].ToString() == "0")
                        {
                            <h3 class="m-0">Usuários dos clientes</h3>
                        }
                        else
                        {
                            <h3 class="m-0">Usuários</h3>
                        }
                    </div>
                </div> <!-- /.row -->
            </div> <!-- /.container-fluid -->
        </div>  <!-- /.content-header -->


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="container-fluid">
                <div class="card card-cyan">
                    <div class="card-header">
                        <div class="col-md-10">
                            <h4>Você tem certeza que deseja excluir o seguinte usuário?</h4>
                        </div>
                    </div> <!-- ./card-header -->
                    <!-- form -->
                    <form role="form">
                        <div class="card-body bg-gray-light">

                            <div class="form-group">
                                @Html.LabelFor(model => model.cus_nome, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.cus_nome, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                    @Html.ValidationMessageFor(model => model.cus_nome, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.cus_sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.cus_sobrenome, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                    @Html.ValidationMessageFor(model => model.cus_sobrenome, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <!-- Row Endereço, Número, Complemento -->
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_endereco, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_endereco, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_endereco, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_numero, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_numero, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_numero, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-5">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_complemento, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_complemento, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_complemento, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- ./row -->
                            <!-- Row Cep, Bairro, Cidade, Estado -->
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_cep, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_cep, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_cep, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_bairro, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_bairro, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_bairro, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_cidade, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_cidade, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_cidade, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_estado, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_estado, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_estado, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- ./row -->
                            <!-- Row Telefone e E-mail -->
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_telefone, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_telefone, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_telefone, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-7">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_email, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_email, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_email, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- ./row -->
                            <!-- Row Usuário e Senha -->
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_usuario, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_usuario, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_usuario, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-5">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cus_senha, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cus_senha, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.cus_senha, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                               


                            </div> <!-- ./row -->
                            <!-- Row Perfil e Ativo -->
                            <div class="row">
                            </div> <!-- ./row -->

                        </div><!-- ./card-body -->
                        <div class="card-footer" style="background-color: #d3dbde; border-bottom-right-radius:inherit; border-bottom-left-radius:inherit;">
                            <div class="row justify-content-center">
                                <div>
                                    <!-- sem essa div vazia, os ítens não estavam ficando no centro da tela -->
                                    <div class="Form-actions col-md-offset-2 col-md-12 ">
                                        <input type="submit" value="Apagar" class="btn btn-danger mx-3 my-1" />
                                        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-warning" })
                                    </div>
                                </div>
                            </div><!-- ./row -->
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>
</div>

ProjetoTesteRafa/Views/ClienteEmpresaUsuario/Index.cshtml
@model IEnumerable<ProjetoTesteRafa.Models.cliente_empresa_usuario>



<div class="container-fluid">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    @if (Session["Empresa"].ToString() == "0")
                    {
                        <h3 class="m-0">Usuários dos clientes</h3>
                    }
                    else
                    {
                        <h3 class="m-0">Usuários</h3>
                    }
                </div>
                <div class="col-sm-6 text-right">
                    @Html.ActionLink("Criar Nova", "Create", "ClienteEmpresaUsuario", null, new { @class = "btn btn-primary" })
                </div>
            </div> <!-- /.row -->
        </div> <!-- /.container-fluid -->
    </div>  <!-- /.content-header -->

    <div class="content">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="card mx-2">
                    @*<div class="card-header">
                            <div class="container-fluid">
                                <div class="row">

                                </div>
                            </div>
                        </div>*@
                    <div class="card-body table-responsive">
                        <table class="table-hover mx-auto table-geral" style="min-width: 770px;">
                            <thead>
                                <tr>
                                    @if (Session["Empresa"].ToString() == "0")
                                    {
                                        <th>
                                            <p class="my-2">Cliente</p>
                                        </th>
                                    }
                                    <th>
                                        @Html.DisplayNameFor(model => model.cus_nome)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.cus_sobrenome)
                                    </th>
                                    <th style="width: 150px;">
                                        @Html.DisplayNameFor(model => model.cus_telefone)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.cus_email)
                                    </th>
                                    @*<th>
                                            @Html.DisplayNameFor(model => model.cus_perfil)
                                        </th>*@
                                    <th style="width: 170px;"></th>
                                </tr>
                            </thead>

                            @foreach (var item in Model)
                            {
                                <tbody style="border-bottom: 5px solid #D6EAF8;">
                                    <tr>
                                        @if (Session["Empresa"].ToString() == "0")
                                        {
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cliente_empresa.cle_razaosocial_principal)
                                            </td>
                                        }
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cus_nome)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cus_sobrenome)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cus_telefone)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cus_email)
                                        </td>
                                        <td>
                                            @Html.ActionLink(" ", "Edit", new { id = item.cus_codigo }, new { @class = "btn btn-success  fas fa-edit", title = "Editar" })
                                            @Html.ActionLink(" ", "Details", new { id = item.cus_codigo }, new { @class = "btn btn-info fas fa-list", title = "Detalhes" })
                                            @Html.ActionLink(" ", "MudarSenha", new { id = item.cus_codigo }, new { @class = "btn btn-danger fas fa-edit", title = "Mudar Senha" })
                                            <div class="tooltip">
                                                "teste"
                                                <span class="tooltiptext">Tooltip text</span>
                                            </div>
                                            @* @Html.ActionLink("Apagar", "Delete", new { id = item.cls_codigo })*@
                                        </td>
                                    </tr>
                                </tbody>
                            }
                        </table>
                    </div>
                </div> <!-- Criar Card -->
            </div> <!-- ./row -->
        </div> <!-- ./container -->
    </div> <!-- ./content -->
</div>