ProjetoTesteRafa/Models/cliente_empresa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjetoTesteRafa.Models
{
    public class cliente_empresa
    {
        [Key]
        public int cle_codigo { get; set; }
        [DisplayName("Razão Social")]
        public string cle_razaosocial_principal { get; set; }
        [DisplayName("Nome Fantasia")]
        public string cle_nomefantasia_principal { get; set; }
        [DisplayName("CNPJ")]
        public string cle_cnpj_principal { get; set; }
        [DisplayName("Ins. Municipal")]
        public string cle_inscricao_municipal { get; set; }
        [DisplayName("Ins. Estadual")]
        public string cle_inscricao_estadual { get; set; }
        [DisplayName("Ramo de Atividade")]
        public string cle_ramo_atividade { get; set; }
        [DisplayName("Número de Funcionários")]
        public string cle_numero_funcionario { get; set; }
        [DisplayName("Validade do Contrato")]
        public string cle_prazo_validade { get; set; }
        [DisplayName("Endereço")]
        public string cle_endereco { get; set; }
        [DisplayName("Número")]
        public int cle_numero { get; set; }
        [DisplayName("Complemento")]
        public string cle_complemento { get; set; }
        [DisplayName("Bairro")]
        public string cle_bairro { get; set; }
        [DisplayName("Cidade")]
        public string cle_cidade { get; set; }
        [DisplayName("Estado")]
        public string cle_estado { get; set; }
        [DisplayName("CEP")]
        public string cle_cep { get; set; }
        [DisplayName("Telefone")]
        public string cle_telefone_principal { get; set; }
        [DisplayName("WebProjetoTesteRafae")]
        public string cle_webProjetoTesteRafae { get; set; }
        [DisplayName("CNPJ Para Cobrança")]
        public string cle_cnpj_cobranca { get; set; }
        [DisplayName("Razão Social Para Cobrança")]
        public string cle_razaosocial_cobranca { get; set; }
        [DisplayName("Contato Financeiro")]
        public string cle_contato_financeiro { get; set; }
        [DisplayName("Telefone Financeiro")]
        public string cle_telefone_financeiro { get; set; }
        [DisplayName("E-mail Financeiro")]
        public string cle_email_financeiro { get; set; }
        [DisplayName("Responsável")]
        public string cle_nome_responsavel { get; set; }
        [DisplayName("E-mail do Responsável")]
        public string cle_email_responsavel { get; set; }
        [DisplayName("Função do Responsável")]
        public string cle_funcao_responsavel { get; set; }
        [DisplayName("Telefone do Responsável")]
        public string cle_telefone_responsavel { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Data Ingresso")]
        public string cle_data_ingresso { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Data Cancelamento")]
        public string cle_data_cancelamento { get; set; }

        [DisplayName("Quantidade de empresas contratadas")]
        public int cle_quantidade_unidade { get; set; }
        [DisplayName("Quantidade de usuários contratados")]
        public int cle_quantidade_usuario { get; set; }

        public int cle_quantidade_unidade_ativa { get; set; }

        public int cle_quantidade_usuario_ativo { get; set; }


        [DisplayName("Grupo empresarial ativo:")]
        public bool cle_ativo { get; set; }


        public virtual IList<cliente_empresa_usuario> cle_empresa_usuario { get; set; }
        
    }
}

ProjetoTesteRafa/Controllers/ClienteEmpresaController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using ProjetoTesteRafa.Models;
using ProjetoTesteRafa.Models.Comum;

namespace ProjetoTesteRafa.Controllers
{
    public class ClienteEmpresaController : Controller
    {

        private DataContext db = new DataContext();


        /*****************************************
         *                                       *
         *                  INDEX                *
         *                                       *
         *****************************************/


        // GET: ClienteEmpresa - Página Index onde serão mostrados os usuários
        [Authorize]
        public async Task<ActionResult> Index()
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                    if (acesso_perfil != null)
                    {
                        if (acesso_perfil.Any(x => x.pua_ler_clienteempresa_index))
                        {
                            return View(await db.cliente_empresa.ToListAsync());  
                        }
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_ler_clienteempresa_index))
                    {
                        return View(await db.cliente_empresa.ToListAsync()); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }



        /*****************************************
         *                                       *
         *                DETAILS                *
         *                                       *
         *****************************************/


        // GET: ClienteEmpresa/Details/5 - Mostrar os detalhes da Empresa selecionada. A numeração no comentário serve para mostrar qual
        //  o índice (o ID do ítem) no banco.
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                    if (acesso_perfil != null)
                    {
                        if (acesso_perfil.Any(x => x.pua_ler_clienteempresa_details))
                        {
                            if (id == null)
                            {
                                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                            }
                            cliente_empresa cliente_empresa = await db.cliente_empresa.FindAsync(id);
                            if (cliente_empresa == null)
                            {
                                return HttpNotFound();
                            }
                            return View(cliente_empresa); 
                        }
                    }
                        return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_ler_clienteempresa_details))
                    {
                        if (id == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                        cliente_empresa cliente_empresa = await db.cliente_empresa.FindAsync(id);
                        if (cliente_empresa == null)
                        {
                            return HttpNotFound();
                        }
                        return View(cliente_empresa); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }



        /*****************************************
         *                                       *
         *                CREATE                 *
         *                                       *
         *****************************************/


        // GET: ClienteEmpresa/Create - Mostrar a criação da Empresa.
        [Authorize]
        public ActionResult Create()
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pua_lerescrever_clienteempresa_create))
                    {
                        ViewBag.Estados = new SelectList(new Estados().ListaEstados(), "data_sigla_estado", "data_nome_estado");
                        return View(); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_lerescrever_clienteempresa_create))
                    {
                        ViewBag.Estados = new SelectList(new Estados().ListaEstados(), "data_sigla_estado", "data_nome_estado");
                        return View(); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }


        // POST: ClienteEmpresaUnidade/Create - Cria a Empresa no banco.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "cle_codigo,cle_razaosocial_principal,cle_nomefantasia_principal,cle_cnpj_principal,cle_inscricao_municipal,cle_inscricao_estadual,cle_ramo_atividade,cle_numero_funcionario,cle_prazo_validade,cle_endereco,cle_numero,cle_complemento,cle_bairro,cle_cidade,cle_estado,cle_cep,cle_telefone_principal,cle_webProjetoTesteRafae,cle_cnpj_cobranca,cle_razaosocial_cobranca,cle_contato_financeiro,cle_telefone_financeiro,cle_email_financeiro,cle_nome_responsavel,cle_email_responsavel,cle_funcao_responsavel,cle_telefone_responsavel,cle_data_ingresso,cle_data_cancelamento,cle_quantidade_unidade,cle_quantidade_usuario,cle_ativo")] cliente_empresa cliente_empresa, string estados)
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pua_lerescrever_clienteempresa_create))
                    {
                        if (ModelState.IsValid)
                        {
                            cliente_empresa.cle_estado = estados;
                            cliente_empresa.cle_ativo = true;
                            db.cliente_empresa.Add(cliente_empresa);
                            await db.SaveChangesAsync();
                            return RedirectToAction("Index");
                        }

                        ViewBag.Estados = new SelectList(new Estados().ListaEstados(), "data_sigla_estado", "data_nome_estado");
                        return View(cliente_empresa); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_lerescrever_clienteempresa_create))
                    {
                        if (ModelState.IsValid)
                        {
                            cliente_empresa.cle_estado = estados;
                            cliente_empresa.cle_ativo = true;
                            db.cliente_empresa.Add(cliente_empresa);
                            await db.SaveChangesAsync();
                            return RedirectToAction("Index");
                        }

                        ViewBag.Estados = new SelectList(new Estados().ListaEstados(), "data_sigla_estado", "data_nome_estado");
                        return View(cliente_empresa); 
                    }

ProjetoTesteRafa/Views/ClienteEmpresa/Index.cshtml
@model IEnumerable<ProjetoTesteRafa.Models.cliente_empresa>

@{
    ViewBag.Title = "Index";
}


<div class="container-fluid">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <h3 class="m-0">Clientes</h3>
                </div>
                <div class="col-sm-6 text-right">
                    @Html.ActionLink("Criar Novo", "Create", "ClienteEmpresa", null, new { @class = "btn btn-primary" })
                </div>
            </div> <!-- /.row -->
        </div> <!-- /.container-fluid -->
    </div>  <!-- /.content-header -->

    <div class="content">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="card mx-2">
                    @*<div class="card-header">
                            <div class="container-fluid">
                                <div class="row">

                                </div>
                            </div>
                        </div>*@
                    <div class="card-body table-responsive">
                        <table class="table-hover mx-auto table-geral" style="min-width: 770px;">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.cle_razaosocial_principal)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.cle_nomefantasia_principal)
                                    </th>
                                    <th style="width: 150px;">
                                        @Html.DisplayNameFor(model => model.cle_cnpj_principal)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.cle_telefone_principal)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.cle_nome_responsavel)
                                    </th>
                                    <th style="width: 170px;"></th>
                                </tr>
                            </thead>


                            @if (@Session["Empresa"].ToString() == "0")
                            {
                                foreach (var item in Model)
                                {
                                    <tbody style="border-bottom: 5px solid #D6EAF8;">
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_razaosocial_principal)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_nomefantasia_principal)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_cnpj_principal)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_telefone_principal)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_nome_responsavel)
                                            </td>
                                            <td>
                                                @Html.ActionLink(" ", "Edit", new { id = item.cle_codigo }, new { @class = "btn btn-success  fas fa-edit", title = "Editar" })
                                                @Html.ActionLink(" ", "Details", new { id = item.cle_codigo }, new { @class = "btn btn-info fas fa-list", title = "Detalhes" })
                                                @*@Html.ActionLink(" ", "MudarSenha", "Usuariogerente", new { id = item.cle_codigo }, new { @class = "btn btn-danger fas fa-edit", title = "Mudar Senha" })*@
                                                <div class="tooltip">
                                                    "teste"
                                                    <span class="tooltiptext">Tooltip text</span>
                                                </div>
                                                @* @Html.ActionLink("Apagar", "Delete", new { id = item.cls_codigo })*@
                                            </td>
                                        </tr>
                                    </tbody>
                                }
                            }
                            else
                            {
                                foreach (var item in Model.Where(m => m.cle_codigo.ToString().Equals(Session["Empresa"].ToString())))
                                {
                                    <tbody style="border-bottom: 5px solid #D6EAF8;">
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_razaosocial_principal)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_nomefantasia_principal)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_cnpj_principal)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_telefone_principal)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cle_nome_responsavel)
                                            </td>
                                            <td>
                                                @Html.ActionLink(" ", "Edit", new { id = item.cle_codigo }, new { @class = "btn btn-success  fas fa-edit", title = "Editar" })
                                                @Html.ActionLink(" ", "Details", new { id = item.cle_codigo }, new { @class = "btn btn-info fas fa-list", title = "Detalhes" })
                                                @*@Html.ActionLink(" ", "MudarSenha", "Usuariogerente", new { id = item.cle_codigo }, new { @class = "btn btn-danger fas fa-edit", title = "Mudar Senha" })*@
                                            </td>
                                        </tr>
                                    </tbody>
                                }
                            }

                        </table>
                    </div>
                </div> <!-- Criar Card -->
            </div> <!-- ./row -->
        </div> <!-- ./container -->
    </div> <!-- ./content -->
</div>