ProjetoTesteRafa/Models/perfil_usuario_acesso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProjetoTesteRafa.Models
{
    public class perfil_usuario_acesso
    {
        [Key]
        public int pua_codigo { get; set; }
        //public bool pua_ler_clienteempresa_create { get; set; }
        [DisplayName("Criar novo grupo empresarial")]
        public bool pua_lerescrever_clienteempresa_create { get; set; }
        [DisplayName("Apagar grupo empresarial")]
        public bool pua_lerescrever_clienteempresa_delete { get; set; }
        //public bool pua_escrever_clienteempresa_delete { get; set; }
        [DisplayName("Accessar informações do grupo empresarial")]
        public bool pua_ler_clienteempresa_details { get; set; }
        //public bool pua_ler_clienteempresa_edit { get; set; }
        [DisplayName("Editar grupo empresarial")]
        public bool pua_lerescrever_clienteempresa_edit { get; set; }
        [DisplayName("Acessar configurações do grupo empresarial")]
        public bool pua_ler_clienteempresa_index { get; set; }


        [DisplayName("Criar novas empresas ou filiais")]
        public bool pua_lerescrever_clienteempresaunidade_create { get; set; }
        //public bool pua_escrever_clienteempresaunidade_create { get; set; }
        [DisplayName("Apagar empresas ou filiais")]
        public bool pua_lerescrever_clienteempresaunidade_delete { get; set; }
        //public bool pua_escrever_clienteempresaunidade_delete { get; set; }
        [DisplayName("Acessar informações de empresas ou filiais")]
        public bool pua_ler_clienteempresaunidade_details { get; set; }
        [DisplayName("Editar empresas ou filiais")]
        public bool pua_lerescrever_clienteempresaunidade_edit { get; set; }
        //public bool pua_escrever_clienteempresaunidade_edit { get; set; }
        [DisplayName("Acessar configurações de empresas ou filiais")]
        public bool pua_ler_clienteempresaunidade_index { get; set; }


        [DisplayName("Criar usuário")]
        public bool pua_lerescrever_clienteempresausuario_create { get; set; }
        //public bool pua_escrever_clienteempresausuario_create { get; set; }
        [DisplayName("Apagar usuário")]
        public bool pua_lerescrever_clienteempresausuario_delete { get; set; }
        //public bool pua_escrever_clienteempresausuario_delete { get; set; }
        [DisplayName("Exibir informações do usuário")]
        public bool pua_ler_clienteempresausuario_details { get; set; }
        [DisplayName("Editar usuário")]
        public bool pua_lerescrever_clienteempresausuario_edit { get; set; }
        //public bool pua_escrever_clienteempresausuario_edit { get; set; }
        [DisplayName("Acessar configurações referente a usuários")]
        public bool pua_ler_clienteempresausuario_index { get; set; }
        [DisplayName("Trocar senha")]
        public bool pua_lerescrever_clienteempresausuario_mudarsenha { get; set; }
        //public bool pua_escrever_clienteempresausuario_mudarsenha { get; set; }


        [DisplayName("Criar novo perfil de vínculo entre usuário e empresa ou filial")]
        public bool pua_lerescrever_perfilusuarioempresa_create { get; set; }
        //public bool pua_escrever_perfilusuarioempresa_create { get; set; }
        [DisplayName("Apagar perfil de vínculo entre usuário e empresa ou filial")]
        public bool pua_lerescrever_perfilusuarioempresa_delete { get; set; }
        //public bool pua_escrever_perfilusuarioempresa_delete { get; set; }
        [DisplayName("Exibir informações do vínculo entre usuário e empresa ou filial")]
        public bool pua_ler_perfilusuarioempresa_details { get; set; }
        [DisplayName("Editar o vínculo entre usuário e empresa ou filial")]
        public bool pua_lerescrever_perfilusuarioempresa_edit { get; set; }
        //public bool pua_escrever_perfilusuarioempresa_edit { get; set; }
        [DisplayName("Acessar configurações de vínculo entre usuário e empresa ou filial")]
        public bool pua_ler_perfilusuarioempresa_index { get; set; }


        [DisplayName("Criar um novo perfil de acesso do usuário")]
        public bool pua_lerescrever_perfilusuarioacesso_create { get; set; }
        //public bool pua_escrever_perfilusuarioacesso_create { get; set; }
        [DisplayName("Apagar um perfil de acesso do usuário")]
        public bool pua_lerescrever_perfilusuarioacesso_delete { get; set; }
        //public bool pua_escrever_perfilusuarioacesso_delete { get; set; }
        [DisplayName("Exibir informações de um perfil de acesso do usuário")]
        public bool pua_ler_perfilusuarioacesso_details { get; set; }
        [DisplayName("Editar perfil de acesso do usuário")]
        public bool pua_lerescrever_perfilusuarioacesso_edit { get; set; }
        //public bool pua_escrever_perfilusuarioacesso_edit { get; set; }
        [DisplayName("Acessar configurações de perfil de acesso do usuário")]
        public bool pua_ler_perfilusuarioacesso_index { get; set; }


        // Vínculo com a tabela de usuários de empresas
        [Display(Name = "Usuário")]
        [ForeignKey("cliente_empresa_usuario")]
        public int pua_usuariocliente { get; set; }
        public virtual cliente_empresa_usuario cliente_empresa_usuario { get; set; }


        //[NotMapped]
        //public bool pua_acesso_variavel { get; set; }
    }
}

ProjetoTesteRafa/Controllers/PerfilUsuarioAcessoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetoTesteRafa.Models;

namespace ProjetoTesteRafa.Controllers
{
    public class PerfilUsuarioAcessoController : Controller
    {
        private DataContext db = new DataContext();


        /*****************************************
         *                                       *
         *                  INDEX                *
         *                                       *
         *****************************************/


        // GET: PerfilUsuarioAcesso - Página Index onde serão mostrados os Acessos dos Usuários
        public async Task<ActionResult> Index()
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                    if (acesso_perfil != null)
                    {
                        if (acesso_perfil.Any(x => x.pua_ler_perfilusuarioacesso_index == true))
                        {
                            var perfil_usuario_acesso = db.perfil_usuario_acesso.Include(p => p.cliente_empresa_usuario);

                            var empresa = (int)Session["Empresa"];
                            var acesso_empresa = perfil_usuario_acesso.Where(x => x.cliente_empresa_usuario.cus_empresa == empresa);

                            return View(await acesso_empresa.ToListAsync());
                        }
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_ler_perfilusuarioacesso_index))
                    {
                        var perfil_usuario_acesso = db.perfil_usuario_acesso.Include(p => p.cliente_empresa_usuario).OrderBy(x => x.cliente_empresa_usuario.cliente_empresa.cle_razaosocial_principal);
                        return View(await perfil_usuario_acesso.ToListAsync()); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }



        /*****************************************
         *                                       *
         *                DETAILS                *
         *                                       *
         *****************************************/


        // GET: PerfilUsuarioAcesso/Details/5 - Mostrar os detalhes dos acessos do usuário selecionado. A numeração no comentário 
        //  serve para mostrar qual o índice (o ID do ítem) no banco.
        public async Task<ActionResult> Details(int? id)
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pua_ler_perfilusuarioacesso_details == true))
                    {
                        if (id == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                        var perfil_usuario_acesso = await db.perfil_usuario_acesso.FindAsync(id);
                        if (perfil_usuario_acesso == null)
                        {
                            return HttpNotFound();
                        }

                        var empresa = (int)Session["Empresa"];
                        var acesso_empresa = perfil_usuario_acesso.cliente_empresa_usuario.cus_empresa.Equals(empresa);

                        if (!acesso_empresa)
                        {
                            return View("~/Views/Shared/_OutraEmpresa.cshtml");
                        }
                        ViewBag.pua_usuariocliente = new SelectList(db.cliente_empresa_usuario, "cus_codigo", "cus_usuario");
                        return View(perfil_usuario_acesso);
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_ler_perfilusuarioacesso_details))
                    {
                        if (id == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                        var perfil_usuario_acesso = await db.perfil_usuario_acesso.FindAsync(id);
                        if (perfil_usuario_acesso == null)
                        {
                            return HttpNotFound();
                        }
                        ViewBag.pua_usuariocliente = new SelectList(db.cliente_empresa_usuario, "cus_codigo", "cus_usuario");
                        return View(perfil_usuario_acesso); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }



        /*****************************************
         *                                       *
         *                CREATE                 *
         *                                       *
         *****************************************/


        // GET: PerfilUsuarioAcesso/Create - Mostrar a criação dos acessos do usuário.
        public ActionResult Create()
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pua_lerescrever_perfilusuarioacesso_create == true))
                    {
                        var empresa = (int)Session["Empresa"];
                        ViewBag.pua_usuariocliente = new SelectList(db.cliente_empresa_usuario.Where(x => x.cus_empresa == empresa), "cus_codigo", "cus_usuario");
                        return View();
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
                else
                {
                    var acesso_perfil_gerente = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil_gerente != null && acesso_perfil_gerente.Any(x => x.pus_lerescrever_perfilusuarioacesso_create))
                    {
                        ViewBag.pua_usuariocliente = new SelectList(db.cliente_empresa_usuario, "cus_codigo", "cus_usuario");
                        return View(); 
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }


        // POST: PerfilUsuarioAcesso/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "pua_codigo,pua_lerescrever_clienteempresaunidade_create,pua_lerescrever_clienteempresaunidade_delete,pua_ler_clienteempresaunidade_details,pua_lerescrever_clienteempresaunidade_edit,pua_ler_clienteempresaunidade_index,pua_lerescrever_clienteempresausuario_create,pua_lerescrever_clienteempresausuario_delete,pua_ler_clienteempresausuario_details,pua_lerescrever_clienteempresausuario_edit,pua_ler_clienteempresausuario_index,pua_lerescrever_clienteempresausuario_mudarsenha,pua_lerescrever_perfilusuarioempresa_create,pua_lerescrever_perfilusuarioempresa_delete,pua_ler_perfilusuarioempresa_details,pua_lerescrever_perfilusuarioempresa_edit,pua_ler_perfilusuarioempresa_index,pua_lerescrever_perfilusuarioacesso_create,pua_lerescrever_perfilusuarioacesso_delete,pua_ler_perfilusuarioacesso_details,pua_lerescrever_perfilusuarioacesso_edit,pua_ler_perfilusuarioacesso_index,pua_usuariocliente")] perfil_usuario_acesso perfil_usuario_acesso) // pua_lerescrever_clienteempresa_create,pua_lerescrever_clienteempresa_delete,pua_ler_clienteempresa_details,pua_lerescrever_clienteempresa_edit,pua_ler_clienteempresa_index
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    var acesso_perfil = new List<perfil_usuario_acesso>(db.perfil_usuario_acesso.ToList().Where(x => x.pua_usuariocliente == (int)Session["UserId"]));

ProjetoTesteRafa/Views/PerfilUsuarioAcesso/Index.cshtml
@model IEnumerable<ProjetoTesteRafa.Models.perfil_usuario_acesso>

@{
    ViewBag.Title = "Index";
}


<div class="container-fluid">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    @if (Session["Empresa"].ToString() == "0")
                    {
                        <h3 class="m-0">Perfis de Acesso do cliente</h3>
                    }
                    else
                    {
                        <h3 class="m-0">Perfis de Acesso</h3>
                    }
                </div>
                <div class="col-sm-6 text-right">
                    @Html.ActionLink("Criar Nova", "Create", "PerfilUsuarioAcesso", null, new { @class = "btn btn-primary" })
                </div>
            </div> <!-- /.row -->
        </div> <!-- /.container-fluid -->
    </div>  <!-- /.content-header -->

    <div class="content">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="card mx-2">
                    @*<div class="card-header">
                            <div class="container-fluid">
                                <div class="row">

                                </div>
                            </div>
                        </div>*@
                    <div class="card-body table-responsive">
                        <table class="table-hover mx-auto table-geral" style="min-width: 770px;">
                            <thead>
                                <tr>
                                    @if (Session["Empresa"].ToString() == "0")
                                    {
                                        <th>
                                            <p class="my-2">Cliente</p>
                                        </th>
                                    }
                                    <th>
                                        <p class="my-2">Empresa</p>
                                    </th>
                                    <th style="width: 150px;">
                                        @Html.DisplayNameFor(model => model.cliente_empresa_usuario.cus_usuario)
                                    </th>
                                    <th style="width: 170px;"></th>
                                </tr>
                            </thead>

                            @foreach (var item in Model)
                            {
                                <tbody style="border-bottom: 5px solid #D6EAF8;">
                                    <tr>
                                        @if (Session["Empresa"].ToString() == "0")
                                        {
                                            <td>
                                                @Html.DisplayFor(modelItem => item.cliente_empresa_usuario.cliente_empresa.cle_razaosocial_principal)
                                            </td>
                                        }
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cliente_empresa_usuario.cus_empresa_unidade)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cliente_empresa_usuario.cus_usuario)
                                        </td>
                                        <td>
                                            @Html.ActionLink(" ", "Edit", new { id = item.pua_codigo }, new { @class = "btn btn-success  fas fa-edit", title = "Editar" })
                                            @Html.ActionLink(" ", "Details", new { id = item.pua_codigo }, new { @class = "btn btn-info fas fa-list", title = "Detalhes" })
                                            @Html.ActionLink(" ", "Delete", new { id = item.pua_codigo }, new { @class = "btn btn-danger fas fa-trash-alt", title = "Apagar" })
                                            <div class="tooltip">
                                                "teste"
                                                <span class="tooltiptext">Tooltip text</span>
                                            </div>
                                            @* @Html.ActionLink("Apagar", "Delete", new { id = item.cls_codigo })*@
                                        </td>
                                    </tr>
                                </tbody>
                            }
                        </table>
                    </div>
                </div> <!-- Criar Card -->
            </div> <!-- ./row -->
        </div> <!-- ./container -->
    </div> <!-- ./content -->
</div>