ProjetoTesteRafa/Models/usuario_gerente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProjetoTesteRafa.Models
{
    public class usuario_gerente
    {
        [Key]
        public int uss_codigo { get; set; }

        [Required(ErrorMessage = "Informe o usuário")]
        [Display(Name = "Usuário")]
        public string uss_usuario { get; set; }

        [Required(ErrorMessage = "Informe a senha")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string uss_senha { get; set; }


        [Display(Name = "Lembrar-me?")]
        public bool uss_lembrar_me { get; set; }

        [Display(Name = "Nome")]
        public string uss_nome { get; set; }

        [Display(Name = "Sorenome")]
        public string uss_sobrenome { get; set; }

        [Display(Name = "Endereço")]
        public string uss_endereco { get; set; }

        [Display(Name = "Número")]
        public string uss_numero { get; set; }

        [Display(Name = "Complemento")]
        public string uss_complemento { get; set; }

        [Display(Name = "Bairro")]
        public string uss_bairro { get; set; }

        [Display(Name = "Cidade")]
        public string uss_cidade { get; set; }

        [Display(Name = "Estado")]
        public string uss_estado { get; set; }

        [Display(Name = "CEP")]
        public string uss_cep { get; set; }

        [Display(Name = "Telefone")]
        public string uss_telefone { get; set; }

        [Display(Name = "E-mail")]
        public string uss_email { get; set; }

        [Display(Name = "Ativar Usuário")]
        public bool uss_ativo { get; set; }

        [NotMapped]
        public string uss_senha_antiga { get; set; }

        [NotMapped]
        public string uss_senha_nova { get; set; }


        //Para fazer a ligação com a entidade 'perfis_usuario'
        public virtual IList<perfis_usuario> perfis_usuario { get; set; }


    }


}

ProjetoTesteRafa/Controllers/UsuarioGerenteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using System.Web.Security;
using ProjetoTesteRafa.Models;
using ProjetoTesteRafa.Models.Comum;

namespace ProjetoTesteRafa.Controllers
{
    public class UsuarioGerenteController : Controller
    {
        private DataContext db = new DataContext();


        /*****************************************
         *                                       *
         *                INDEX                  *
         *                                       *
         *****************************************/


        // GET: Usuariogerente - Página Index onde serão mostrados os usuários
        [Authorize]
        public async Task<ActionResult> Index()
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    return View("~/Views/Shared/_OutraEmpresa.cshtml");
                }
                else
                {
                    var acesso_perfil = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pus_ler_usuariogerente_index))
                    {
                        var usuario_gerente = db.usuario_gerente.Include(u => u.perfis_usuario).OrderBy(x => x.uss_nome);
                        return View(await usuario_gerente.ToListAsync());
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }



        /*****************************************
         *                                       *
         *                DETAILS                *
         *                                       *
         *****************************************/


        // GET: Usuariogerente/Details/5 - Mostrar os detalhes do usuário selecionado. A numeração no comentário serve para mostrar qual
        //  o índice (o ID do ítem) no banco.
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    return View("~/Views/Shared/_OutraEmpresa.cshtml");
                }
                else
                {
                    var acesso_perfil = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pus_ler_usuariogerente_details))
                    {
                        if (id == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                        usuario_gerente usuario_gerente = await db.usuario_gerente.FindAsync(id);
                        if (usuario_gerente == null)
                        {
                            return HttpNotFound();
                        }

                        return View(usuario_gerente);
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }



        /*****************************************
         *                                       *
         *                CREATE                 *
         *                                       *
         *****************************************/


        // GET: Usuariogerente/Create - Mostrar a criação do usuário.
        [Authorize]
        public ActionResult Create()
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    return View("~/Views/Shared/_OutraEmpresa.cshtml");
                }
                else
                {
                    var acesso_perfil = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pus_lerescrever_usuariogerente_create))
                    {
                        ViewBag.Estados = new SelectList(new Estados().ListaEstados(), "data_sigla_estado", "data_nome_estado");
                        return View();
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }


        // POST: Usuariogerente/Create - Cria o usuário no banco.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "uss_codigo,uss_usuario,uss_senha,uss_lembrar_me,uss_nome,uss_sobrenome,uss_endereco,uss_numero,uss_complemento,uss_bairro,uss_cidade,uss_estado,uss_cep,uss_telefone,uss_email,uss_ativo,uss_perfil")] usuario_gerente usuario_gerente, string estados)
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    return View("~/Views/Shared/_OutraEmpresa.cshtml");
                }
                else
                {
                    var acesso_perfil = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pus_lerescrever_usuariogerente_create))
                    {
                        if (ModelState.IsValid)
                        {
                            // checa no banco se o usuário já existe e impede a criação de um novo com o mesmo nome de usuário
                            var checar = db.usuario_gerente.FirstOrDefault(s => s.uss_usuario == usuario_gerente.uss_usuario);


                            if (checar == null)
                            {
                                usuario_gerente.uss_estado = estados;
                                usuario_gerente.uss_senha = ManagerController.CriarMD5(usuario_gerente.uss_senha);
                                usuario_gerente.uss_ativo = true;
                                db.usuario_gerente.Add(usuario_gerente);
                                await db.SaveChangesAsync();
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                ViewBag.UsuarioErro = "Usuário já cadastrado";
                            }
                        }
                        ViewBag.Estados = new SelectList(new Estados().ListaEstados(), "data_sigla_estado", "data_nome_estado");
                        return View(usuario_gerente);
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }

            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }



        /*****************************************
         *                                       *
         *                EDIT                   *
         *                                       *
         *****************************************/


        // GET: Usuariogerente/Edit/5 - Mostrar a página de edição do usuário selecionado. A numeração no comentário serve para mostrar qual
        //  o índice (o ID do ítem) no banco.
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (Session["Empresa"] != null || Session["UserId"] != null)
            {
                if (Session["Empresa"].ToString() != "0")
                {
                    return View("~/Views/Shared/_OutraEmpresa.cshtml");
                }
                else
                {
                    var acesso_perfil = new List<perfis_usuario>(db.perfis_usuario.ToList().Where(x => x.pus_usuariogerente == (int)Session["UserId"]));

                    if (acesso_perfil != null && acesso_perfil.Any(x => x.pus_lerescrever_usuariogerente_edit))
                    {
                        if (id == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                        usuario_gerente usuario_gerente = await db.usuario_gerente.FindAsync(id);
                        if (usuario_gerente == null)
                        {
                            return HttpNotFound();
                        }
                        ViewBag.Estados = new SelectList(new Estados().ListaEstados(), "data_sigla_estado", "data_nome_estado");
                        return View(usuario_gerente);
                    }
                    return View("~/Views/Shared/_SemAutorizacao.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Manager");
            }
        }


        // POST: Usuariogerente/Edit/5 - Salva no banco as edições efetuadas no usuário selecionado. A numeração no comentário serve para mostrar qual
        //  o índice (o ID do ítem) no banco.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]

ProjetoTesteRafa/Views/UsuarioGerente/Index.cshtml
@model IEnumerable<ProjetoTesteRafa.Models.usuario_gerente>


@{
    ViewBag.Title = "Index";
}


@if (@Session["Empresa"].ToString() == "0")
{
    <div class="content">
        <div class="container-fluid">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h3 class="m-0">Usuários gerente</h3>
                        </div>
                        <div class="col-sm-6 text-right">
                            @Html.ActionLink("Criar Novo", "Create", "UsuarioGerente", null, new { @class = "btn btn-primary" })
                        </div>
                    </div> <!-- /.row -->
                </div> <!-- /.container-fluid -->
            </div>  <!-- /.content-header -->

            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="card mx-2">
                        @*<div class="card-header">
                                <div class="container-fluid">
                                    <div class="row">
                                    </div>
                                </div>
                            </div>*@
                        <div class="card-body table-responsive">
                            <table class="table-hover mx-auto table-geral" style="min-width: 770px;">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.uss_nome)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.uss_sobrenome)
                                        </th>
                                        <th style="width: 150px;">
                                            @Html.DisplayNameFor(model => model.uss_telefone)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.uss_email)
                                        </th>
                                        @*<th>
                                            @Html.DisplayNameFor(model => model.uss_perfil)
                                        </th>*@
                                        <th style="width: 170px;"></th>
                                    </tr>
                                </thead>

                                @foreach (var item in Model)
                                {
                                    <tbody style="border-bottom: 5px solid #D6EAF8;">
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.uss_nome)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.uss_sobrenome)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.uss_telefone)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.uss_email)
                                            </td>
                                            @*<td>
                                                @Html.DisplayFor(modelItem => item.uss_perfil)
                                            </td>*@
                                            <td>
                                                @Html.ActionLink(" ", "Edit", new { id = item.uss_codigo }, new { @class = "btn btn-success  fas fa-edit", title = "Editar" })
                                                @Html.ActionLink(" ", "Details", new { id = item.uss_codigo }, new { @class = "btn btn-info fas fa-list", title = "Detalhes" })
                                                @*@Html.ActionLink(" ", "MudarSenha", "UsuarioGerente", new { id = item.uss_codigo }, new { @class = "btn btn-danger fas fa-edit", title = "Mudar Senha" })*@
                                                <div class="tooltip">
                                                    "teste"
                                                    <span class="tooltiptext">Tooltip text</span>
                                                </div>
                                                @* @Html.ActionLink("Apagar", "Delete", new { id = item.cls_codigo })*@
                                            </td>
                                        </tr>
                                    </tbody>
                                }

                            </table>
                        </div>
                    </div> <!-- Criar Card -->
                </div> <!-- ./row -->
            </div> <!-- ./container -->
        </div>
    </div>
}
else
{
    <h1> VOCÊ NÃO TEM PERMISSÃO PARA UTILIZAR ESSA FUNÇÃO </h1>
}

ProjetoTesteRafa/Views/UsuarioGerente/Login.cshtml
@model ProjetoTesteRafa.Models.usuario_gerente

@{
    ViewBag.Title = "Entrar";
}

@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<style>
    html, body {
        margin: 0;
        padding: 0;
        height: 100%;
        max-height: 100%;
        min-width: 420px;
    }

    .login,
    .image {
        object-fit: cover;
        min-height: 92.5vh;
    }

    .bg-image {
        /* background-image: url('https://res.cloudinary.com/mhmd/image/upload/v1555917661/art-colorful-contemporary-2047905_dxtao7.jpg');*/
        background-size: cover;
        background-position: center center;
    }
</style>

@using (Html.BeginForm("Login", "UsuarioGerente", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="container-fluid">
        <div class="row no-gutter">
            <!-- A metade com a Imagem -->
            <div class="col-md-6 d-none d-md-flex bg-image"></div>


            <!-- A metade com o conteúdo -->
            <div class="col-md-6 bg-light">
                <div class="login d-flex align-items-center py-5">

                    <!-- Conteúdo-->
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-10 col-xl-7 mx-auto">
                                <h3 class="display-4">Bem-Vindo!</h3>
                                <p class="text-muted mb-4">Entre com seus dados para acessar.</p>

                                <!-- Começo do Form para entrar com os dados -->
                                <form>
                                    <div class="form-group mb-3">
                                        @Html.TextBoxFor(m => m.uss_usuario, new { @class = "form-control rounded-pill border-0 shadow-sm px-4", type = "text", placeholder = "Nome de Usuário" })
                                        @Html.ValidationMessageFor(m => m.uss_usuario, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group mb-3">
                                        @Html.PasswordFor(m => m.uss_senha, new { @class = "form-control rounded-pill border-0 shadow-sm px-4 text-primary", type = "password", placeholder = "Senha" })
                                        @Html.ValidationMessageFor(m => m.uss_senha, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="custom-control custom-checkbox mb-3">
                                        @Html.CheckBoxFor(m => m.uss_lembrar_me, new { @class = "custom-control-input", type = "checkbox" })
                                        @Html.LabelFor(m => m.uss_lembrar_me, new { @class = "custom-control-label" })
                                    </div>
                                    <input type="submit" value="Entrar" class="btn btn-primary btn-block text-uppercase mb-2 rounded-pill shadow-sm" />

                                    @*<button type="submit" class="btn btn-primary btn-block text-uppercase mb-2 rounded-pill shadow-sm">Sign in</button>*@
                                    <div class="text-center d-flex justify-content-between mt-4">
                                        <div>
                                            <p> Não tem cadastro ainda?</p>
                                        </div>

                                        <div>
                                            <p>
                                                @Html.ActionLink("Criar uma conta", "Registrar")
                                            </p>
                                        </div>
                                    </div>
                                </form><!-- End -->
                            </div>
                        </div>
                    </div><!-- End -->

                </div>
                <div class="text-center col-lg-10 col-xl-7 mx-auto text-muted mb-4">
                    <p>&copy; @DateTime.Now.Year - Projeto Teste Rafa</p>
                </div>
            </div><!-- End -->

        </div>
    </div>

}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoTesteRafa/Views/UsuarioGerente/MudarSenha.cshtml
@model ProjetoTesteRafa.Models.usuario_gerente

@{
    ViewBag.Title = "Mudar Senha";
}


<div class="content pb-1">
    <div class="container-fluid">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <h3 class="m-0">Usuários</h3>
                    </div>
                </div> <!-- /.row -->
            </div> <!-- /.container-fluid -->
        </div>  <!-- /.content-header -->


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.uss_codigo)
            @Html.HiddenFor(model => model.uss_usuario)
            @Html.HiddenFor(model => model.uss_lembrar_me)
            @Html.HiddenFor(model => model.uss_nome)
            @Html.HiddenFor(model => model.uss_sobrenome)
            @Html.HiddenFor(model => model.uss_endereco)
            @Html.HiddenFor(model => model.uss_numero)
            @Html.HiddenFor(model => model.uss_complemento)
            @Html.HiddenFor(model => model.uss_bairro)
            @Html.HiddenFor(model => model.uss_cidade)
            @Html.HiddenFor(model => model.uss_estado)
            @Html.HiddenFor(model => model.uss_cep)
            @Html.HiddenFor(model => model.uss_telefone)
            @Html.HiddenFor(model => model.uss_email)
            @Html.HiddenFor(model => model.uss_ativo)
            @Html.HiddenFor(model => model.uss_perfil)

            <div class="container-fluid">
                <div class="card card-cyan">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-12">
                                <h4>Digite a nova senha para o usuário </h4>
                            </div>
                        </div>
                    </div> <!-- ./card-header -->
                    <!-- form -->
                    <form role="form">
                        <div class="card-body bg-gray-light">

                            <div class="row  justify-content-center">
                                <div class="form-group ">
                                    @Html.LabelFor(model => model.uss_nome, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.uss_nome, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                        @Html.ValidationMessageFor(model => model.uss_nome, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div> <!-- ./row -->

                            <div class="row">
                                <div class="form-group col-md-6">
                                    @Html.LabelFor(model => model.uss_senha, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div>
                                        @Html.EditorFor(model => model.uss_senha, new { htmlAttributes = new { @class = "form-control", required = "required", title = "Informe seu primeiro nome" } })
                                        @Html.ValidationMessageFor(model => model.uss_senha, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group col-md-6 py-1">
                                    <h6 class="control-label col-md-12" style="font-weight: bold">Confirme a senha</h6>
                                    <div>
                                        <input data-val="true" data-val-equalto="A senha e a senha de confirmação não correspondem." data-val-equalto-other="*.uss_senha"
                                               data-val-required="Informe a senha de confirmação" id="ConfirmPassword" name="ConfirmPassword" type="password"
                                               class="form-control" />
                                        <span class="field-validation-valid error text-danger" data-valmsg-for="ConfirmPassword" data-valmsg-replace="true"></span>
                                    </div>
                                </div>

                            </div> <!-- ./row -->
                        </div> <!-- ./card-body -->


                        <div class="card-footer" style="background-color: #d3dbde; border-bottom-right-radius:inherit; border-bottom-left-radius:inherit;">
                            <div class="row justify-content-center">
                                <div>
                                    <!-- sem essa div vazia, os ítens não estavam ficando no centro da tela -->
                                    <div class="col-md-offset-2 col-md-12">
                                        <input type="submit" value="Atualizar" class="btn btn-success mx-3 my-1" />
                                        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
                                    </div>
                                </div>
                            </div><!-- ./row -->
                        </div>
                    </form>
                </div> <!-- ./card -->
            </div>
        }
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}